# Site settings
title: "6.874 Computational Systems Biology: Deep Learning in the Life Sciences"
description: "Course materials and notes for MIT class 6.802 / 6.874 / 20.390 / 20.490 / HST.506 Computational Systems Biology: Deep Learning in the Life Sciences"
baseurl: ""
url: "https://mit6874.github.io"
#url: "127.0.0.1"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-tactile